//
// Proposals: the shapes, the bounds, and the form token.
//
// docs/PROPOSALS.md §8 build step 2 is the `break` type only — "here is a case
// this division cannot classify". It is first because it is the most valuable
// and the easiest to submit: it needs a case, not a replacement structure.
//
// Nothing here knows about the other four types. When they arrive they bring
// their own payload shape and their own bounds, and this file gains a branch
// rather than a generalisation written before there was anything to generalise.
//
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Bounds ----------------------------------------------------------------------

const BODY_MAX = 4000;          // §4: "the argument, markdown, 4000 chars"
const CASE_MAX = 1000;
const SOURCE_MAX = 300;
const SOURCES_MAX = 20;

// §4: "Honeypot field plus minimum time-on-form of 20 seconds".
const MIN_SECONDS_ON_FORM = 20;

// A form left open overnight and submitted in the morning is a real person, so
// this is generous. It exists so a token cannot be minted once and reused by a
// script for a month.
const FORM_TOKEN_MAX_AGE_MS = 24 * 60 * 60 * 1000;


// The atlas -------------------------------------------------------------------
//
// §4: `node_path` "resolves in the current atlas". The atlas is YAML under
// version control and is not in this database, so the set of valid paths is
// generated by scripts/atlas-manifest.mjs and committed into api/. Read once at
// startup: it changes when the service is redeployed and not otherwise.

const MANIFEST = (() => {
    const file = path.join(__dirname, '..', 'atlas-manifest.json');
    try {
        const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
        return { paths: new Set(parsed.paths), nodes: parsed.nodes || {} };
    } catch (err) {
        // Refusing to start is right. Without this file every proposal would be
        // rejected as pointing at an unknown node, which looks like a bad
        // submission rather than a broken deploy.
        throw new Error(
            `Could not read atlas-manifest.json (${err.message}). ` +
            'Run `npm run atlas:manifest` at the repository root and commit the result.'
        );
    }
})();

function knownNodePath(value) {
    return typeof value === 'string' && MANIFEST.paths.has(value);
}

// What the review queue shows beside a submission (§6). Null for a path that
// has left the atlas since the proposal was made — which the queue says out
// loud rather than rendering an empty panel.
function nodeState(value) {
    return MANIFEST.nodes[value] || null;
}


// Payloads, per type ----------------------------------------------------------
//
// §4 gives the payload shape for `subdivide` and for no other type: "For
// subdivide, payload carries the proposed children, each with the same six
// fields a node carries." The other three are described only by what they say:
//
//   redefine   this node's definition, inclusion or exclusion is wrong
//   relocate   this node belongs under a different parent
//   merge      these siblings are not distinct and should be one
//
// So their shapes are designed here rather than transcribed, and kept as small
// as the sentence allows. Each carries the change being proposed and nothing
// else; the argument for it is `body`, which every type has.

// Rule 01's ceiling and Rule 05's floor, which are the two the count can break.
const CHILDREN_MAX = 7;
const CHILDREN_MIN = 2;
const CHILD_NAME_MAX = 80;
const CHILD_TEXT_MAX = 1000;

function parentOf(path) {
    const cut = path.lastIndexOf('/');
    return cut < 0 ? null : path.slice(0, cut);
}

// Paths are slash-joined ids, so descent is a prefix test. The trailing slash
// matters: `legal-x` must not read as a descendant of `legal`.
function isSelfOrDescendant(candidate, ancestor) {
    return candidate === ancestor || candidate.startsWith(`${ancestor}/`);
}

function childIdsOf(path) {
    const node = MANIFEST.nodes[path];
    return node ? node.children.map((c) => c.id) : [];
}

// A list of non-empty strings, or a problem. Absent counts as empty, because
// the six fields are "key required, may be empty" on a real node too.
function stringListProblem(value, label, max = CHILD_TEXT_MAX) {
    if (value === undefined || value === null) return null;
    if (!Array.isArray(value)) return `${label} must be a list.`;
    for (const entry of value) {
        if (typeof entry !== 'string') return `${label} must be a list of lines.`;
        if (entry.trim().length > max) {
            return `Each ${label.toLowerCase()} line is limited to ${max} characters.`;
        }
    }
    return null;
}

function cleanList(value) {
    if (!Array.isArray(value)) return [];
    return value.map((s) => String(s).trim()).filter((s) => s !== '');
}

function subdivideProblem(body) {
    const children = body.children;
    if (!Array.isArray(children)) return 'A subdivision needs its proposed components.';

    // Rule 05 before Rule 01: one child is not a small division, it is not a
    // division. The client refuses both before sending and quotes the rule;
    // these are the same refusals restated where they cannot be skipped.
    if (children.length < CHILDREN_MIN) {
        return `Rule 05 — a division needs at least ${CHILDREN_MIN} parts. `
             + 'One part divides nothing.';
    }
    if (children.length > CHILDREN_MAX) {
        return `Rule 01 — at most ${CHILDREN_MAX} components. `
             + `This proposes ${children.length}.`;
    }

    for (const child of children) {
        if (!child || typeof child !== 'object') return 'Each component must be a block.';

        const name = typeof child.name === 'string' ? child.name.trim() : '';
        if (name === '') return 'Every component needs a name.';
        if (name.length > CHILD_NAME_MAX) {
            return `A component name is limited to ${CHILD_NAME_MAX} characters.`;
        }

        if (typeof child.definition === 'string'
            && child.definition.trim().length > CHILD_TEXT_MAX) {
            return `A component definition is limited to ${CHILD_TEXT_MAX} characters.`;
        }

        // An empty definition is a declared gap and is allowed, as it is on a
        // real node. The form warns; it does not refuse.
        const listProblem =
            stringListProblem(child.inclusion, 'Inclusion')
            || stringListProblem(child.exclusion, 'Exclusion')
            || stringListProblem(child.sources, 'Sources')
            || stringListProblem(child.boundary_cases, 'Boundary cases')
            || stringListProblem(child.uncertainty, 'Uncertainty');
        if (listProblem) return listProblem;
    }
    return null;
}

function redefineProblem(body) {
    const hasDefinition = typeof body.definition === 'string' && body.definition.trim() !== '';
    const hasInclusion = Array.isArray(body.inclusion) && cleanList(body.inclusion).length > 0;
    const hasExclusion = Array.isArray(body.exclusion) && cleanList(body.exclusion).length > 0;

    if (!hasDefinition && !hasInclusion && !hasExclusion) {
        return 'A redefinition needs a replacement: a definition, an inclusion list, '
             + 'or an exclusion list.';
    }
    if (hasDefinition && body.definition.trim().length > BODY_MAX) {
        return `The replacement definition is limited to ${BODY_MAX} characters.`;
    }
    return stringListProblem(body.inclusion, 'Inclusion')
        || stringListProblem(body.exclusion, 'Exclusion');
}

function relocateProblem(body, nodePath) {
    const target = typeof body.newParent === 'string' ? body.newParent.trim() : '';
    if (target === '') return 'A relocation needs the parent it should move under.';
    if (!knownNodePath(target)) {
        return 'That parent is not in the atlas. Check the path from the node page URL.';
    }
    // Moving a node under itself or under one of its own descendants would make
    // the tree stop being a tree. Refused here rather than discovered by
    // whoever tries to apply it.
    if (isSelfOrDescendant(target, nodePath)) {
        return target === nodePath
            ? 'A node cannot be its own parent.'
            : 'That parent is inside the node being moved, which would make a loop.';
    }
    if (target === parentOf(nodePath)) {
        return 'That is already its parent.';
    }
    return null;
}

function mergeProblem(body, nodePath) {
    const siblings = Array.isArray(body.siblings) ? body.siblings.map((s) => String(s).trim()) : null;
    if (!siblings) return 'A merge needs the components it would join.';
    if (siblings.length < 2) return 'A merge needs at least two components.';
    if (new Set(siblings).size !== siblings.length) {
        return 'The same component is listed twice.';
    }

    // node_path is the parent whose division changes, so the components named
    // have to be its children. Naming the parent is what makes "siblings"
    // checkable at all — two ids on their own do not say what they are under.
    const known = new Set(childIdsOf(nodePath));
    if (known.size === 0) {
        return 'That node has no components to merge. Choose the node they sit under.';
    }
    for (const id of siblings) {
        if (!known.has(id)) {
            return `"${id}" is not a component of that node.`;
        }
    }
    if (siblings.length > known.size) {
        return 'That is more components than the node has.';
    }
    return null;
}

// Returns a problem sentence, or null. `break` is checked by caseProblem.
function payloadProblem(type, body, nodePath) {
    if (type === 'break') return caseProblem(body.case);
    if (type === 'subdivide') return subdivideProblem(body);
    if (type === 'redefine') return redefineProblem(body);
    if (type === 'relocate') return relocateProblem(body, nodePath);
    if (type === 'merge') return mergeProblem(body, nodePath);
    return 'Unknown proposal type.';
}

// What is stored. Built from scratch rather than passed through, so a field
// nobody validated cannot reach the column.
function buildPayload(type, body) {
    if (type === 'break') {
        return { case: String(body.case).trim() };
    }
    if (type === 'subdivide') {
        return {
            children: body.children.map((c) => ({
                name: String(c.name).trim(),
                definition: typeof c.definition === 'string' ? c.definition.trim() : '',
                inclusion: cleanList(c.inclusion),
                exclusion: cleanList(c.exclusion),
                sources: cleanList(c.sources),
                boundary_cases: cleanList(c.boundary_cases),
                uncertainty: cleanList(c.uncertainty),
            })),
        };
    }
    if (type === 'redefine') {
        const out = {};
        if (typeof body.definition === 'string' && body.definition.trim() !== '') {
            out.definition = body.definition.trim();
        }
        if (cleanList(body.inclusion).length) out.inclusion = cleanList(body.inclusion);
        if (cleanList(body.exclusion).length) out.exclusion = cleanList(body.exclusion);
        return out;
    }
    if (type === 'relocate') {
        return { newParent: String(body.newParent).trim() };
    }
    if (type === 'merge') {
        return { siblings: body.siblings.map((s) => String(s).trim()) };
    }
    return {};
}

// A one-line description of what a payload proposes, for the queue and the node
// page. Neither of those should be reaching into payload shapes themselves.
function summarisePayload(type, payload) {
    if (!payload) return '';
    if (type === 'break') return payload.case ?? '';
    if (type === 'subdivide') {
        const names = (payload.children ?? []).map((c) => c.name);
        return `Divide into ${names.length}: ${names.join(', ')}`;
    }
    if (type === 'redefine') {
        const changed = ['definition', 'inclusion', 'exclusion'].filter((k) => payload[k]);
        return `Rewrite the ${changed.join(', ')}`;
    }
    if (type === 'relocate') return `Move under ${payload.newParent}`;
    if (type === 'merge') return `Merge ${(payload.siblings ?? []).join(' + ')}`;
    return '';
}


// The six rules --------------------------------------------------------------
//
// `decision_rule` in §4 is "which of the six rules it failed, if any". The
// numbers and names are the ones scripts/build.mjs prints on every node page,
// and they have to stay the same two things: a rejection that cites Rule 04
// has to mean what the node page means by Rule 04.
//
// Rules 02, 03 and 04 are judgements and are not automated anywhere. That is
// exactly why they are the ones a rejection most often has to name.

const RULES = [
    ['01', 'At most seven'],
    ['02', 'Mutually exclusive'],
    ['03', 'Collectively exhaustive'],
    ['04', 'Equal abstraction'],
    ['05', 'Decomposable or terminal'],
    ['06', 'Justified in writing'],
];

const RULE_IDS = new Set(RULES.map(([id]) => id));

// Absent is allowed — §6 says a rejection names a rule "where one applies", and
// a break can be rejected because the case is not a case rather than because
// the division broke a rule.
function decisionRuleProblem(value) {
    if (value === undefined || value === null || value === '') return null;
    if (!RULE_IDS.has(value)) {
        return `That is not one of the six rules. Expected one of ${[...RULE_IDS].join(', ')}.`;
    }
    return null;
}

// §6: accept and reject both require a reason, and both are published. The
// bound is generous; the point is that it exists and that empty is refused.
const REASON_MAX = 4000;

function decisionReasonProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'A decision needs a reason. It is published with the decision.';
    }
    if (value.trim().length > REASON_MAX) {
        return `The reason is limited to ${REASON_MAX} characters.`;
    }
    return null;
}


// Field checks ----------------------------------------------------------------
//
// Each returns a sentence to show the person, or null. Same shape as
// src/accounts.js, so a route reads the same way whichever it is calling.

function nodePathProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'Which node is this about?';
    }
    if (!knownNodePath(value.trim())) {
        return 'That node is not in the atlas. Check the path from the node page URL.';
    }
    return null;
}

function caseProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'A break needs a case: the thing the division cannot classify.';
    }
    if (value.trim().length > CASE_MAX) {
        return `The case is limited to ${CASE_MAX} characters. The argument below has room.`;
    }
    return null;
}

function bodyProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'Say why the division cannot classify it.';
    }
    if (value.trim().length > BODY_MAX) {
        return `The argument is limited to ${BODY_MAX} characters.`;
    }
    return null;
}

function displayAsProblem(value) {
    if (value !== 'name' && value !== 'anonymous') {
        return 'Choose whether to publish under your display name or anonymously.';
    }
    return null;
}

// Absent, empty, or a list of non-empty strings. Empty is allowed: §4 warns on
// the form when there are no sources but does not refuse, because a break can
// be a case nobody has written up.
function sourcesProblem(value) {
    if (value === undefined || value === null) return null;
    if (!Array.isArray(value)) return 'Sources must be a list.';
    if (value.length > SOURCES_MAX) {
        return `At most ${SOURCES_MAX} sources.`;
    }
    for (const entry of value) {
        if (typeof entry !== 'string') return 'Each source must be a line of text.';
        if (entry.trim().length > SOURCE_MAX) {
            return `Each source is limited to ${SOURCE_MAX} characters.`;
        }
    }
    return null;
}

function cleanSources(value) {
    if (!Array.isArray(value)) return [];
    return value.map((s) => String(s).trim()).filter((s) => s !== '');
}


// The form token --------------------------------------------------------------
//
// §4 asks for a minimum time-on-form of 20 seconds, server-side. The form is a
// static page, so the server cannot know when it was opened unless it says so
// itself: GET /atlas/proposals/new issues a token carrying the issue time and
// an HMAC of it, and the submission carries it back.
//
// An elapsed-milliseconds number sent by the page would have been simpler and
// would have checked nothing — the value a script sends is the value it wants
// to send. This is signed, so the only way to satisfy the check is to have
// asked for the form and waited.

const SECRET = (() => {
    if (process.env.FORM_SECRET) return process.env.FORM_SECRET;
    // A per-process secret still works, and keeps the service deployable
    // without a new variable. The cost is that tokens issued before a restart
    // are refused afterwards, and the person is asked to reload — so it is
    // worth setting FORM_SECRET in production, and worth saying why here
    // rather than failing on boot over something recoverable.
    if (process.env.NODE_ENV === 'production') {
        console.warn(
            'FORM_SECRET is not set — proposal form tokens will not survive a restart.'
        );
    }
    return crypto.randomBytes(32).toString('hex');
})();

function sign(issuedAt) {
    return crypto.createHmac('sha256', SECRET).update(String(issuedAt)).digest('hex');
}

function issueFormToken(now = Date.now()) {
    return `${now}.${sign(now)}`;
}

// Returns a sentence or null. Deliberately does not distinguish "forged" from
// "expired" to the caller beyond what the person needs to do about it.
function formTokenProblem(token, now = Date.now()) {
    if (typeof token !== 'string' || !token.includes('.')) {
        return 'This form has expired. Reload the page and try again.';
    }

    const [issuedAtRaw, mac] = token.split('.', 2);
    const issuedAt = Number(issuedAtRaw);
    if (!Number.isFinite(issuedAt)) {
        return 'This form has expired. Reload the page and try again.';
    }

    const expected = sign(issuedAtRaw);
    const a = Buffer.from(String(mac), 'utf8');
    const b = Buffer.from(expected, 'utf8');
    if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {
        return 'This form has expired. Reload the page and try again.';
    }

    const age = now - issuedAt;
    if (age > FORM_TOKEN_MAX_AGE_MS || age < 0) {
        return 'This form has expired. Reload the page and try again.';
    }
    if (age < MIN_SECONDS_ON_FORM * 1000) {
        return 'Take a moment longer over it — a proposal is read by a person.';
    }
    return null;
}


// The public shape ------------------------------------------------------------
//
// What a submitter is told back about their own proposal. Not the review
// queue's shape: decision_reason and the account behind an anonymous
// submission belong to §6 and are not built yet.

function publicProposal(row) {
    return {
        id: String(row.id),
        nodePath: row.node_path,
        type: row.type,
        displayAs: row.display_as,
        status: row.status,
        createdAt: row.created_at,
    };
}


module.exports = {
    BODY_MAX,
    CASE_MAX,
    SOURCE_MAX,
    SOURCES_MAX,
    REASON_MAX,
    MIN_SECONDS_ON_FORM,
    FORM_TOKEN_MAX_AGE_MS,
    RULES,
    CHILDREN_MAX,
    CHILDREN_MIN,
    CHILD_NAME_MAX,
    CHILD_TEXT_MAX,
    knownNodePath,
    nodeState,
    parentOf,
    childIdsOf,
    payloadProblem,
    buildPayload,
    summarisePayload,
    decisionRuleProblem,
    decisionReasonProblem,
    nodePathProblem,
    caseProblem,
    bodyProblem,
    displayAsProblem,
    sourcesProblem,
    cleanSources,
    issueFormToken,
    formTokenProblem,
    publicProposal,
    pathCount: MANIFEST.paths.size,
};
